import type { Lesson } from "@/lib/types";

/**
 * Учебный контент намеренно хранится в коде, а не в D1.
 * Готовые MP3 лежат в public/audio. Границы реплик выставлены по паузам
 * в каждой записи и остаются легко редактируемыми рядом с текстом.
 */
export const lessons: Lesson[] = [
  {
    id: "introduction-001",
    level: 1,
    block: 1,
    blockTitle: "Знакомство",
    number: 1,
    title: "Первое знакомство",
    description: "Приветствие, представление и вопрос о делах",
    goal: "Научиться здороваться, представляться и спрашивать, как дела.",
    audioUrl: "/audio/block-01-lesson-01.mp3",
    audioStatus: "ready",
    durationMs: 18_364,
    lines: [
      { id: "introduction-001-line-01", speaker: "خَالِدٌ", arabic: "السَّلَامُ عَلَيْكُمْ.", translation: "Мир вам.", startMs: 0, endMs: 1_681 },
      { id: "introduction-001-line-02", speaker: "يُوسُفُ", arabic: "وَعَلَيْكُمُ السَّلَامُ.", translation: "И вам мир.", startMs: 1_681, endMs: 3_875 },
      { id: "introduction-001-line-03", speaker: "خَالِدٌ", arabic: "اِسْمِي خَالِدٌ، مَا اسْمُكَ؟", translation: "Меня зовут Халид. Как тебя зовут?", startMs: 3_875, endMs: 7_170 },
      { id: "introduction-001-line-04", speaker: "يُوسُفُ", arabic: "اِسْمِي يُوسُفُ.", translation: "Меня зовут Юсуф.", startMs: 7_170, endMs: 9_140 },
      { id: "introduction-001-line-05", speaker: "خَالِدٌ", arabic: "كَيْفَ حَالُكَ؟", translation: "Как твои дела?", startMs: 9_140, endMs: 11_012 },
      { id: "introduction-001-line-06", speaker: "يُوسُفُ", arabic: "بِخَيْرٍ، وَالْحَمْدُ لِلَّهِ. وَأَنْتَ؟", translation: "Хорошо, хвала Аллаху. А ты?", startMs: 11_012, endMs: 15_489 },
      { id: "introduction-001-line-07", speaker: "خَالِدٌ", arabic: "بِخَيْرٍ، وَالْحَمْدُ لِلَّهِ.", translation: "Хорошо, хвала Аллаху.", startMs: 15_489, endMs: 18_364 },
    ],
    shortAnalysis: [
      { arabic: "اِسْمٌ", explanation: "имя." },
      { arabic: "اِسْمِي", explanation: "моё имя. Окончание ـي означает «мой»." },
      { arabic: "اِسْمُكَ", explanation: "твоё имя при обращении к мужчине. Окончание ـكَ означает «твой»." },
      { arabic: "حَالُكَ", explanation: "твоё состояние, твои дела." },
      { arabic: "وَأَنْتَ؟", explanation: "а ты?" },
    ],
  },
  {
    id: "introduction-003",
    level: 1,
    block: 1,
    blockTitle: "Знакомство",
    number: 2,
    title: "Откуда ты?",
    description: "Страна, регион, город и национальность",
    goal: "Научиться спрашивать и говорить, откуда ты.",
    audioUrl: "/audio/block-01-lesson-02.mp3",
    audioStatus: "ready",
    durationMs: 18_678,
    lines: [
      { id: "introduction-003-line-01", speaker: "خَالِدٌ", arabic: "مِنْ أَيْنَ أَنْتَ؟", translation: "Откуда ты?", startMs: 0, endMs: 1_787 },
      { id: "introduction-003-line-02", speaker: "يُوسُفُ", arabic: "أَنَا مِنْ تَتَارِسْتَانَ، مِنْ قَازَانَ. وَأَنْتَ؟", translation: "Я из Татарстана, из Казани. А ты?", startMs: 1_787, endMs: 7_359 },
      { id: "introduction-003-line-03", speaker: "خَالِدٌ", arabic: "أَنَا مِنْ مِصْرَ، مِنَ الْقَاهِرَةِ.", translation: "Я из Египта, из Каира.", startMs: 7_359, endMs: 10_759 },
      { id: "introduction-003-line-04", speaker: "خَالِدٌ", arabic: "هَلْ أَنْتَ رُوسِيٌّ؟", translation: "Ты русский?", startMs: 10_759, endMs: 12_990 },
      { id: "introduction-003-line-05", speaker: "يُوسُفُ", arabic: "لَا، أَنَا مِصْرِيٌّ. وَأَنْتَ؟", translation: "Нет, я египтянин. А ты?", startMs: 12_990, endMs: 17_262 },
      { id: "introduction-003-line-06", speaker: "خَالِدٌ", arabic: "أَنَا رُوسِيٌّ.", translation: "Я русский.", startMs: 17_262, endMs: 18_678 },
    ],
    shortAnalysis: [
      { arabic: "مِنْ أَيْنَ؟", explanation: "откуда?" },
      { arabic: "أَنَا مِنْ…", explanation: "я из…" },
      { arabic: "هَلْ", explanation: "ставится в начале вопроса, на который отвечают «да» или «нет»." },
      { arabic: "رُوسِيٌّ", explanation: "русский." },
      { arabic: "مِصْرِيٌّ", explanation: "египтянин." },
    ],
  },
  {
    id: "introduction-004",
    level: 1,
    block: 1,
    blockTitle: "Знакомство",
    number: 3,
    title: "Где ты живёшь?",
    description: "Город и место проживания",
    goal: "Научиться спрашивать и говорить, где ты живёшь.",
    audioUrl: "/audio/block-01-lesson-03.mp3",
    audioStatus: "ready",
    durationMs: 20_114,
    lines: [
      { id: "introduction-004-line-01", speaker: "خَالِدٌ", arabic: "أَيْنَ تَسْكُنُ الآنَ؟", translation: "Где ты сейчас живёшь?", startMs: 0, endMs: 2_502 },
      { id: "introduction-004-line-02", speaker: "يُوسُفُ", arabic: "أَسْكُنُ فِي قَازَانَ.", translation: "Я живу в Казани.", startMs: 2_502, endMs: 5_564 },
      { id: "introduction-004-line-03", speaker: "خَالِدٌ", arabic: "هَلْ تَسْكُنُ فِي وَسَطِ الْمَدِينَةِ؟", translation: "Ты живёшь в центре города?", startMs: 5_564, endMs: 9_015 },
      { id: "introduction-004-line-04", speaker: "يُوسُفُ", arabic: "لَا، أَسْكُنُ قَرِيبًا مِنَ الْجَامِعَةِ.", translation: "Нет, я живу недалеко от университета.", startMs: 9_015, endMs: 13_840 },
      { id: "introduction-004-line-05", speaker: "خَالِدٌ", arabic: "هَلْ تُحِبُّ قَازَانَ؟", translation: "Тебе нравится Казань?", startMs: 13_840, endMs: 16_816 },
      { id: "introduction-004-line-06", speaker: "يُوسُفُ", arabic: "نَعَمْ، أُحِبُّهَا كَثِيرًا.", translation: "Да, она мне очень нравится.", startMs: 16_816, endMs: 20_114 },
    ],
    shortAnalysis: [
      { arabic: "تَسْكُنُ", explanation: "ты живёшь." },
      { arabic: "أَسْكُنُ", explanation: "я живу. Начальная تـ здесь указывает на «ты», а أَ — на «я»." },
      { arabic: "قَرِيبًا مِنْ", explanation: "рядом с, недалеко от." },
      { arabic: "تُحِبُّ", explanation: "ты любишь, тебе нравится." },
      { arabic: "أُحِبُّهَا", explanation: "я люблю её, она мне нравится. Окончание ـهَا означает «её»." },
    ],
  },
  {
    id: "introduction-005",
    level: 1,
    block: 1,
    blockTitle: "Знакомство",
    number: 4,
    title: "Новый знакомый",
    description: "Представление друга и знакомство",
    goal: "Научиться представлять друга и знакомиться с новым человеком.",
    audioUrl: "/audio/block-01-lesson-04.mp3",
    audioStatus: "ready",
    durationMs: 19_801,
    lines: [
      { id: "introduction-005-line-01", speaker: "خَالِدٌ", arabic: "يَا يُوسُفُ، هَذَا صَدِيقِي أَحْمَدُ.", translation: "Юсуф, это мой друг Ахмад.", startMs: 0, endMs: 2_617 },
      { id: "introduction-005-line-02", speaker: "يُوسُفُ", arabic: "أَهْلًا يَا أَحْمَدُ، أَنَا يُوسُفُ.", translation: "Привет, Ахмад. Я Юсуф.", startMs: 2_617, endMs: 5_358 },
      { id: "introduction-005-line-03", speaker: "أَحْمَدُ", arabic: "أَهْلًا يَا يُوسُفُ.", translation: "Привет, Юсуф.", startMs: 5_358, endMs: 6_922 },
      { id: "introduction-005-line-04", speaker: "يُوسُفُ", arabic: "مِنْ أَيْنَ أَنْتَ؟", translation: "Откуда ты?", startMs: 6_922, endMs: 8_703 },
      { id: "introduction-005-line-05", speaker: "أَحْمَدُ", arabic: "أَنَا مِنْ تُرْكِيَا، وَأَسْكُنُ الآنَ فِي قَازَانَ.", translation: "Я из Турции, а сейчас живу в Казани.", startMs: 8_703, endMs: 14_502 },
      { id: "introduction-005-line-06", speaker: "يُوسُفُ", arabic: "هَلْ تَدْرُسُ هُنَا؟", translation: "Ты здесь учишься?", startMs: 14_502, endMs: 16_313 },
      { id: "introduction-005-line-07", speaker: "أَحْمَدُ", arabic: "نَعَمْ، أَدْرُسُ مَعَ خَالِدٍ فِي الْجَامِعَةِ.", translation: "Да, я учусь с Халидом в университете.", startMs: 16_313, endMs: 19_801 },
    ],
    shortAnalysis: [
      { arabic: "هَذَا", explanation: "это, при указании на мужчину." },
      { arabic: "صَدِيقٌ", explanation: "друг." },
      { arabic: "صَدِيقِي", explanation: "мой друг. Окончание ـي означает «мой»." },
      { arabic: "تَدْرُسُ", explanation: "ты учишься." },
      { arabic: "أَدْرُسُ", explanation: "я учусь." },
      { arabic: "هُنَا", explanation: "здесь." },
      { arabic: "مَعَ", explanation: "с, вместе с." },
    ],
  },
  {
    id: "languages-005",
    level: 1,
    block: 2,
    blockTitle: "Языки и общение",
    number: 5,
    title: "На каких языках ты говоришь?",
    description: "Языки, на которых вы говорите",
    goal: "Научиться называть языки, на которых ты говоришь.",
    audioUrl: "/audio/block-02-lesson-05.mp3",
    audioStatus: "ready",
    durationMs: 11_886,
    lines: [
      { id: "languages-005-line-01", speaker: "خَالِدٌ", arabic: "هَلْ تَتَكَلَّمُ الرُّوسِيَّةَ؟", translation: "Ты говоришь по-русски?", startMs: 0, endMs: 2_094 },
      { id: "languages-005-line-02", speaker: "يُوسُفُ", arabic: "نَعَمْ، أَتَكَلَّمُ الرُّوسِيَّةَ وَالتَّتَرِيَّةَ.", translation: "Да, я говорю по-русски и по-татарски.", startMs: 2_094, endMs: 6_374 },
      { id: "languages-005-line-03", speaker: "خَالِدٌ", arabic: "هَلْ تَتَكَلَّمُ الْعَرَبِيَّةَ أَيْضًا؟", translation: "Ты также говоришь по-арабски?", startMs: 6_374, endMs: 9_178 },
      { id: "languages-005-line-04", speaker: "يُوسُفُ", arabic: "نَعَمْ، أَتَكَلَّمُهَا قَلِيلًا.", translation: "Да, немного говорю.", startMs: 9_178, endMs: 11_886 },
    ],
    shortAnalysis: [
      { arabic: "تَتَكَلَّمُ", explanation: "ты говоришь." },
      { arabic: "أَتَكَلَّمُ", explanation: "я говорю." },
      { arabic: "أَيْضًا", explanation: "также, тоже." },
      { arabic: "أَتَكَلَّمُهَا", explanation: "я говорю на нём. Окончание ـهَا заменяет слово «арабский язык»." },
      { arabic: "قَلِيلًا", explanation: "немного." },
    ],
  },
  {
    id: "languages-006",
    level: 1,
    block: 2,
    blockTitle: "Языки и общение",
    number: 6,
    title: "Ты понимаешь по-арабски?",
    description: "Как сказать, что вы понимаете или не понимаете",
    goal: "Научиться говорить, понимаешь ты или нет.",
    audioUrl: "/audio/block-02-lesson-06.mp3",
    audioStatus: "ready",
    durationMs: 11_468,
    lines: [
      { id: "languages-006-line-01", speaker: "خَالِدٌ", arabic: "هَلْ تَفْهَمُ الْعَرَبِيَّةَ؟", translation: "Ты понимаешь арабский?", startMs: 0, endMs: 2_064 },
      { id: "languages-006-line-02", speaker: "يُوسُفُ", arabic: "أَفْهَمُ بَعْضَ الْكَلِمَاتِ.", translation: "Я понимаю некоторые слова.", startMs: 2_064, endMs: 4_697 },
      { id: "languages-006-line-03", speaker: "خَالِدٌ", arabic: "هَلْ تَفْهَمُ هَذَا السُّؤَالَ؟", translation: "Ты понимаешь этот вопрос?", startMs: 4_697, endMs: 7_122 },
      { id: "languages-006-line-04", speaker: "يُوسُفُ", arabic: "لَا، أَعِدْ مِنْ فَضْلِكَ.", translation: "Нет, повтори, пожалуйста.", startMs: 7_122, endMs: 10_208 },
      { id: "languages-006-line-05", speaker: "خَالِدٌ", arabic: "حَسَنًا.", translation: "Хорошо.", startMs: 10_208, endMs: 11_468 },
    ],
    shortAnalysis: [
      { arabic: "تَفْهَمُ", explanation: "ты понимаешь." },
      { arabic: "أَفْهَمُ", explanation: "я понимаю." },
      { arabic: "بَعْضُ الْكَلِمَاتِ", explanation: "некоторые слова." },
      { arabic: "هَذَا السُّؤَالُ", explanation: "этот вопрос." },
      { arabic: "أَعِدْ", explanation: "повтори." },
      { arabic: "مِنْ فَضْلِكَ", explanation: "пожалуйста, при обращении к мужчине." },
    ],
  },
  {
    id: "languages-007",
    level: 1,
    block: 2,
    blockTitle: "Языки и общение",
    number: 7,
    title: "Кто он и откуда?",
    description: "Рассказ о другом человеке",
    goal: "Научиться рассказывать о другом человеке.",
    audioUrl: "/audio/block-02-lesson-07.mp3",
    audioStatus: "ready",
    durationMs: 14_524,
    lines: [
      { id: "languages-007-line-01", speaker: "يُوسُفُ", arabic: "مَنْ هَذَا؟", translation: "Кто это?", startMs: 0, endMs: 1_589 },
      { id: "languages-007-line-02", speaker: "خَالِدٌ", arabic: "هَذَا صَدِيقِي عُمَرُ.", translation: "Это мой друг Умар.", startMs: 1_589, endMs: 4_723 },
      { id: "languages-007-line-03", speaker: "يُوسُفُ", arabic: "مِنْ أَيْنَ هُوَ؟", translation: "Откуда он?", startMs: 4_723, endMs: 7_211 },
      { id: "languages-007-line-04", speaker: "خَالِدٌ", arabic: "هُوَ مِنْ تُرْكِيَا.", translation: "Он из Турции.", startMs: 7_211, endMs: 9_857 },
      { id: "languages-007-line-05", speaker: "يُوسُفُ", arabic: "مَا لُغَتُهُ؟", translation: "Какой у него родной язык?", startMs: 9_857, endMs: 12_461 },
      { id: "languages-007-line-06", speaker: "خَالِدٌ", arabic: "لُغَتُهُ التُّرْكِيَّةُ.", translation: "Его родной язык — турецкий.", startMs: 12_461, endMs: 14_524 },
    ],
    shortAnalysis: [
      { arabic: "مَنْ هَذَا؟", explanation: "кто это?" },
      { arabic: "هُوَ", explanation: "он." },
      { arabic: "مِنْ أَيْنَ هُوَ؟", explanation: "откуда он?" },
      { arabic: "لُغَةٌ", explanation: "язык." },
      { arabic: "لُغَتُهُ", explanation: "его язык. Окончание ـهُ означает «его»." },
      { arabic: "التُّرْكِيَّةُ", explanation: "турецкий язык." },
    ],
  },
  {
    id: "languages-008",
    level: 1,
    block: 2,
    blockTitle: "Языки и общение",
    number: 8,
    title: "Новый студент в группе",
    description: "Знакомство студента с преподавателем",
    goal: "Научиться говорить, что ты новый студент и изучаешь арабский.",
    audioUrl: "/audio/block-02-lesson-08.mp3",
    audioStatus: "ready",
    durationMs: 20_114,
    lines: [
      { id: "languages-008-line-01", speaker: "الْأُسْتَاذُ", arabic: "أَهْلًا بِكَ. هَلْ أَنْتَ طَالِبٌ جَدِيدٌ؟", translation: "Добро пожаловать. Ты новый студент?", startMs: 0, endMs: 4_390 },
      { id: "languages-008-line-02", speaker: "عُمَرُ", arabic: "نَعَمْ، أَنَا طَالِبٌ جَدِيدٌ.", translation: "Да, я новый студент.", startMs: 4_390, endMs: 8_675 },
      { id: "languages-008-line-03", speaker: "الْأُسْتَاذُ", arabic: "هَلْ تَدْرُسُ الْعَرَبِيَّةَ؟", translation: "Ты изучаешь арабский?", startMs: 8_675, endMs: 11_656 },
      { id: "languages-008-line-04", speaker: "عُمَرُ", arabic: "نَعَمْ، أَدْرُسُ الْعَرَبِيَّةَ.", translation: "Да, я изучаю арабский.", startMs: 11_656, endMs: 15_211 },
      { id: "languages-008-line-05", speaker: "الْأُسْتَاذُ", arabic: "حَسَنًا، اِجْلِسْ هُنَا.", translation: "Хорошо, садись здесь.", startMs: 15_211, endMs: 18_877 },
      { id: "languages-008-line-06", speaker: "عُمَرُ", arabic: "شُكْرًا.", translation: "Спасибо.", startMs: 18_877, endMs: 20_114 },
    ],
    shortAnalysis: [
      { arabic: "طَالِبٌ", explanation: "студент." },
      { arabic: "جَدِيدٌ", explanation: "новый." },
      { arabic: "تَدْرُسُ", explanation: "ты изучаешь, учишься." },
      { arabic: "أَدْرُسُ", explanation: "я изучаю, учусь." },
      { arabic: "اِجْلِسْ", explanation: "садись." },
      { arabic: "هُنَا", explanation: "здесь." },
    ],
  },
];

export function getLesson(lessonId: string) {
  return lessons.find((lesson) => lesson.id === lessonId) ?? null;
}
